answers:
  outputs:
    dev:
      dataset: dbt_sdk
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: abstract-botany-434416-k4
      threads: 60
      type: bigquery
  target: dev
